[features]
seeds = true
skip-lint = false
[programs.devnet]
oasis = "ARG2PKVAXGAwLJHqBDojnwk3A2HgsL4H8CBPSwwahPL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/david/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
