[features]
seeds = true
skip-lint = false
[programs.localnet]
oasis = "B7oHWTujVfjuyahjLgzroVAHNphsRgTM343JQDncJFwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/david/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
